Develop
word-a-day/word-a-day pull request #4
Opened 2019-01-27 22:39 UTC by Tcalura

2019-01-28 10:05 UTC, pedrozath requested changes

2019-01-28 10:05 UTC, pedrozath commented on config/database.yml
> +  password: trocar@123
cara, em todos os lugares que trampei, o de praxe era acesso local sem senha. acho um pouco desnecessário ter senha, o que acha?

2019-01-28 10:05 UTC, pedrozath commented on db/migrate/20190127214102_create_words.rb
> +      t.integer :grammarClass
:grammar_class

2019-01-28 10:05 UTC, pedrozath commented on app/models/user.rb
> +class User < ApplicationRecord
```suggestion
class User < ApplicationRecord
  has_many :words, through: :exercises
```

2019-01-28 10:05 UTC, pedrozath commented on db/migrate/20190127213739_create_users.rb
> +      t.string :firstName
as colunas tem que ser todas com underscore, não camel cased

first_name
last_name
telegram_id
etc

2019-01-29 11:33 UTC, Tcalura commented on config/database.yml
> +  password: trocar@123
a gente pode usar sim sem psswd, fechado!

2019-02-20 16:07 UTC, merged